steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
          python-version: '3.x'
          architecture: 'x64'
    - name: poetry action
      uses: abatilo/actions-poetry@v2.0.0
    - name: run poetry --help to verify action working
      run: poetry --help
